// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migrationWriterEdit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrationWriterEdit));
        
        string IMigrationMetadata.Id
        {
            get { return "202105150710284_migrationWriterEdit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
